name: Code Review Inline with Gemini

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get install jq -y
          gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract inline diffs
        run: |
          mkdir -p diffs
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git fetch origin ${{ github.event.pull_request.head.ref }}

          files=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.head.ref }})
          
          for file in $files; do
            dir="diffs/$(dirname "$file")"
            mkdir -p "$dir"
            git diff origin/${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.head.ref }} -- "$file" > "$dir/$(basename "$file").diff"
          done

      - name: Gemini Inline Review Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          for diff_file in $(find diffs -name "*.diff"); do
            file_path="${diff_file#diffs/}"
            file_path="${file_path%.diff}"

            # Get changed lines (simple heuristic: starts with '+', not '+++')
            grep "^+[^+]" "$diff_file" | sed 's/^+//' > tmp_added_lines.txt
            mapfile -t added_lines < tmp_added_lines.txt

            index=1
            while IFS= read -r line; do
              # Create prompt
              prompt="Você é um revisor de código experiente. Analise a seguinte linha do arquivo \`$file_path\`:

                $line

                Comente apenas se encontrar algo com impacto relevante, como:
                - bugs
                - falhas de lógica
                - violação de boas práticas críticas
                - problemas de segurança
                - problemas de performance
                - inconsistência com o estilo do projeto

                Evite sugestões genéricas, estéticas ou irrelevantes.

                Responda com a estrutura:

                Severidade: [Alta, Média, Baixa]  
                Sugestão: [descrição clara e objetiva da sugestão]

                Responda sempre em português brasileiro."

              response=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}" \
                -H "Content-Type: application/json" \
                -d '{
                      "contents": [
                        {
                          "parts": [
                            { "text": "'"$prompt"'" }
                          ]
                        }
                      ]
                    }')

              feedback=$(echo "$response" | jq -r '.candidates[0].content.parts[0].text')

              if [ "$feedback" != "null" ] && [ -n "$feedback" ] && [ "$feedback" != "" ]; then
                echo "Comentando sobre $file_path linha $index"

                gh pr comment "$PR_NUMBER" \
                --body "💡 **Sugestão para o arquivo \`$file_path\`:**\n\n$feedback"
              fi

              index=$((index + 1))
            done < tmp_added_lines.txt
          done
